"""Add location column to machine

Revision ID: 0dab4a85594f
Revises: 577b702b7bd0
Create Date: 2026-07-08 10:24:18.367653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dab4a85594f'
down_revision: Union[str, Sequence[str], None] = '577b702b7bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('location', sa.String(), server_default='Line A', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'location')
    # ### end Alembic commands ###
