"""add index to logs.machine_id

Revision ID: 4291a7e9c56f
Revises: 686d980fe1c1
Create Date: 2026-08-01 13:00:53.848645

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4291a7e9c56f"
down_revision: str | Sequence[str] | None = "686d980fe1c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_logs_machine_id"), "logs", ["machine_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_logs_machine_id"), table_name="logs")
    # ### end Alembic commands ###
